# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure(2) do |config|

  # Base Ubuntu 14.04 Box
  config.vm.box = "ubuntu/trusty64"


  # Sync Folders
  config.vm.synced_folder "../", "/home/vagrant/"
  config.vm.synced_folder "../deployment", "/home/vagrant/deployment"

  # Forwarding Ports
  config.vm.network "forwarded_port", guest: 8000, host: 8001 # Django

  # VirtualBox Provider
  config.vm.provider "virtualbox" do |vb|

    vb.name = "trumpratings"

    # Customize the amount of memory on the VM:
    vb.memory = "1024"
   end

  # Deployment scripts
  config.vm.provision "shell", path: "kickstart.sh", run: "always"
  config.vm.provision "shell", path: "setup-python3-env.sh", run: "always", privileged: false
  config.vm.provision "shell", inline: "sudo su postgres > deployment/psql_setup.sql"

end
