# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure(2) do |config|

  # Base Ubuntu 14.04 Box
  config.vm.box = "ubuntu/trusty64"


  # Sync Folders
  config.vm.synced_folder "../code", "/home/vagrant/code"
  config.vm.synced_folder "../deployment", "/home/vagrant/deployment"

  # Forwarding Ports
  config.vm.network "forwarded_port", guest: 5000, host: 5000 # Flask
  config.vm.network "forwarded_port", guest: 5432, host: 5431 # Postgres

  # VirtualBox Provider
  config.vm.provider "virtualbox" do |vb|

    vb.name = "trumpratings"

    # Customize the amount of memory on the VM:
    vb.memory = "1024"
   end

  # Deployment scripts
  config.vm.provision "shell", path: "kickstart.sh", run: "always"
  config.vm.provision "shell", path: "setup-python3-env.sh", run: "always", privileged: true
  config.vm.provision "shell", path: "setup-db.sh", run: "always", privileged: false


end
